bump
YaccConstructor/YC.QuickGraph.Query pull request #4
Opened 2017-08-28 14:25 UTC by likeanowl

2017-09-01 07:36 UTC, gsvgit requested changes

2017-09-01 07:36 UTC, gsvgit commented on tests/YC.QuickGraph.Query.Tests/Tests.fs
> +        Assert.AreEqual(42, 42)
Что?)

2017-09-01 07:36 UTC, gsvgit commented on tests/YC.QuickGraph.Query.Tests/Tests.fs
> +    for v in vertices do
Кажется, мы где-то обсуждали, что добавлять вершины и рёбра можно проще.

2017-09-01 07:36 UTC, gsvgit commented on tests/YC.QuickGraph.Query.Tests/Tests.fs
> +    generate (grammarFile)
А зачем скобки?

2017-09-01 11:09 UTC, likeanowl commented on tests/YC.QuickGraph.Query.Tests/Tests.fs
> +        Assert.AreEqual(42, 42)
Заглушка просто, на днях закончу с тестами

2017-09-03 13:18 UTC, likeanowl commented on tests/YC.QuickGraph.Query.Tests/Tests.fs
> +    for v in vertices do
Это старое, видимо, просто забыл убрать.

2017-09-05 23:24 UTC, likeanowl commented
Проблема с зависимостями: почему-то не подтягиваются FsYacc и CustomHashSet автоматически из пакетов. Как это пофиксить?

2017-11-11 15:54 UTC, closed without merging